#!/usr/bin/env python3

import argparse
import os
import re
import sys
from tarfile import open as tar_open
from typing import NoReturn

DEFAULT_PATTERNS = [
    re.compile(r"^lib(|32|64)\/lib[^/]*\.so(\.\d+)*$")
]
ORCHESTRA_SHARE = os.path.join(f"{os.environ['DESTDIR']}{os.environ['ORCHESTRA_ROOT']}", "share/orchestra")
SAVE_DIRECTORY = os.path.join(ORCHESTRA_SHARE, "save_for_later")


def fail(msg: str) -> NoReturn:
    sys.stderr.write(f"{msg}\n")
    sys.exit(1)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input", type=str, help="Input Directory")
    parser.add_argument("name", type=str)
    parser.add_argument("pattern", type=str, nargs='*')
    return parser.parse_args()


def main():
    args = parse_args()
    if len(args.pattern) > 0:
        patterns = [re.compile(p) for p in args.pattern]
    else:
        patterns = DEFAULT_PATTERNS

    if args.input is not None:
        if not os.path.isdir(args.input):
            fail("Input directory does not exist")
        os.chdir(args.input)

    selected_files = []
    for root, _, files in os.walk('.'):
        for file in files:
            full_file = os.path.join(root, file)[2:]
            if any(p.match(full_file) for p in patterns):
                selected_files.append(full_file)

    if not os.path.isdir(SAVE_DIRECTORY):
        os.makedirs(SAVE_DIRECTORY, exist_ok=True)

    target_file = os.path.join(SAVE_DIRECTORY, f"{args.name}.tar.xz")
    with tar_open(target_file, "w:xz", preset=3) as tarfile:
        for file in selected_files:
            tarfile.add(file)
    for file in selected_files:
        os.remove(file)


if __name__ == "__main__":
    main()
