#!/usr/bin/env python3

#
# This file is distributed under the MIT License. See LICENSE.md for details.
#

import argparse
import atexit
import os
import queue
import struct
import sys
from concurrent.futures import ThreadPoolExecutor
from hashlib import file_digest
from pathlib import Path
from shutil import rmtree
from subprocess import PIPE, run
from tempfile import mkdtemp
from threading import Thread
from typing import Callable

import yaml
from common import BinaryEntry, get_s3_client, hash_file
from xdg import xdg_cache_home

SCRIPT_DIR = Path(__file__).parent.resolve()


#
# Start of filter definitions
#


def filter_pe(filename: Path):
    with open(filename, "rb") as f:
        mz_header = f.read(2)
        if mz_header != b"MZ":
            return False
        f.seek(0x3C, os.SEEK_SET)  # 0x3C contains PE offset
        pe_offset = struct.unpack("<i", f.read(4))[0]  # Offset is encoded as a little-endian int
        f.seek(pe_offset, os.SEEK_SET)
        return f.read(4) == b"PE\x00\x00"


def filter_elf(filename: Path):
    with open(filename, "rb") as f:
        magic = f.read(4)
        return magic == b"\x7FELF"


def filter_macho(filename: Path):
    magics = (b"\xfe\xed\xfa\xce", b"\xce\xfa\xed\xfe", b"\xfe\xed\xfa\xcf", b"\xcf\xfa\xed\xfe")
    with open(filename, "rb") as f:
        magic = f.read(4)
        return magic in magics


def _filter_windows_filename(filename: Path):
    suffix = filename.suffix
    suffix_blacklist = (".msstyles", ".mun", ".rs", ".rll", ".vdm", ".odf", ".lex", ".FIL")
    return not (suffix.startswith(".mui") or suffix in suffix_blacklist)


def filter_windows(filename: Path):
    return filter_pe(filename) and _filter_windows_filename(filename)


FILTERS = {"pe": filter_pe, "elf": filter_elf, "macho": filter_macho, "windows": filter_windows}

#
# End of filter definitions
#


def process_path(path: Path, filter_function: Callable[[Path], bool], out_queue: queue.Queue):
    if not filter_function(path):
        return

    with open(path, "rb") as f:
        digest = file_digest(f, "sha256")
        size = f.seek(0, os.SEEK_END)
    out_queue.put(BinaryEntry("", size, 0, digest.hexdigest(), path.resolve()))


def fix_entry(entry: BinaryEntry):
    sorted_sources = sorted(entry.sources)
    name = os.path.basename(sorted_sources[0]) + f"_{entry.hash[:8]}"
    proc = run(
        ["revng", "mass-testing", "dump-sections", "--text-size", str(entry._path)],
        text=True,
        stdout=PIPE,
        check=True,
    )
    text_size = int(proc.stdout)
    return BinaryEntry(name, entry.size, text_size, entry.hash, entry._path, sorted_sources)


class EntryMergeThread(Thread):
    def __init__(self, queue: queue.Queue, result_dict, root: Path):
        super().__init__()
        self.queue = queue
        self.result_dict = result_dict
        self.root = root

    def run(self):
        while True:
            item = self.queue.get()
            if item is None:
                break

            relative_path = str(item._path.relative_to(self.root))
            if item.hash not in self.result_dict:
                self.result_dict[item.hash] = item
                item.sources.append(relative_path)
            else:
                self.result_dict[item.hash].sources.append(relative_path)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--extractor", help="Extractor")
    parser.add_argument("--filter", help="Filter")
    parser.add_argument("--output-dir", type=Path, help="Directory where files will be unpacked")
    parser.add_argument("--scratch-dir", type=Path, help="Scratch directory")
    parser.add_argument("--no-upload", action="store_true", help="Do not upload")
    parser.add_argument("-C", "--comment", help="Additional comment to leave in the output")
    parser.add_argument("input", help="Input File/Directory/URL")
    parser.add_argument("output", help="Output file")
    return parser.parse_args()


def main():
    args = parse_args()

    # Setup scratch dir
    if args.scratch_dir is not None:
        scratch_dir = args.scratch_dir.resolve()
    else:
        scratch_dir = xdg_cache_home() / "revng_mass_testing"
    scratch_dir.mkdir(exist_ok=True)

    # Setup s3 unless --no-upload is provided
    if not args.no_upload:
        s3_client = get_s3_client()

    # Download input, if necessary
    if args.input.startswith("http://") or args.input.startswith("https://"):
        temp_download = mkdtemp(dir=scratch_dir)
        atexit.register(rmtree, temp_download, ignore_errors=True)
        run(["wget", args.input], check=True, cwd=temp_download)
        input_ = Path(temp_download) / os.path.basename(args.input)
    else:
        input_ = Path(args.input)

    # Hash input if it is a file
    if input_.is_file():
        input_hash = hash_file(input_)
    else:
        input_hash = None

    # Setup output-dir, make it so that it's deleted at the end unless the user
    # specifies --no-upload
    if args.output_dir is not None:
        workdir = args.output_dir
    else:
        workdir = Path(mkdtemp(dir=scratch_dir))
        atexit.register(rmtree, workdir, ignore_errors=True)

    # Run the extractor is specified
    if args.extractor is not None:
        extractor = SCRIPT_DIR / f"extractors/{args.extractor}"
        assert extractor.is_file(), "Extractor does not exist"
        run([str(extractor), input_, str(workdir)], check=True)
        target = workdir
    else:
        target = input_

    # Setup filter function
    if args.filter is not None:
        assert args.filter in FILTERS, "Specified filter does not exist"
        filter_ = FILTERS[args.filter]
    else:

        def filter_(path):
            return True

    assert target.is_dir(), "Target must be a directory"

    result_raw = {}
    result_queue = queue.Queue()
    merge_thread = EntryMergeThread(result_queue, result_raw, target)
    merge_thread.start()
    with ThreadPoolExecutor() as executor:
        for dirname, directories, filenames in os.walk(target):
            dirname_path = Path(dirname)
            for filename in filenames:
                file_path = dirname_path / filename
                if file_path.is_symlink():
                    continue
                executor.submit(process_path, file_path, filter_, result_queue)

    result_queue.put(None)
    merge_thread.join()

    result = []
    with ThreadPoolExecutor() as executor:
        for value in executor.map(fix_entry, result_raw.values()):
            result.append(value)

    result.sort(key=lambda x: x.hash)
    with open(args.output, "w") as f:
        f.write(f"# File generated by {os.path.basename(sys.argv[0])}\n")
        f.write(f"# Script hash: {hash_file(sys.argv[0])}\n")
        if args.extractor is not None:
            f.write(f"# Extractor: {args.extractor}\n")
        if args.filter is not None:
            f.write(f"# Filter: {args.filter}\n")
        f.write(f"# Input: {args.input}\n")
        if input_hash is not None:
            f.write(f"# Input hash: {input_hash}\n")
        if args.comment:
            f.write(f"# Comment: {args.comment}\n")
        yaml.safe_dump([v.to_dict() for v in result], f, width=float("inf"))

    if args.no_upload:
        return

    with ThreadPoolExecutor() as executor:
        jobs = executor.map(lambda e: s3_client.put_object(e.hash, str(e._path), True), result)
        # force iterating on jobs so that if there's an exception it is raised
        for job in jobs:
            pass


if __name__ == "__main__":
    main()
