#!/usr/bin/env python3

#
# This file is distributed under the MIT License. See LICENSE.md for details.
#

import argparse
import csv
import re
import sqlite3
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input", help="Input database (main.db)")
    parser.add_argument("output", help="Output csv file")
    args = parser.parse_args()

    includes = []
    conn = sqlite3.connect(args.input)
    query = "SELECT name, input_name, elapsed_time, max_rss FROM main WHERE status = 'OK'"
    ok_binaries = conn.execute(query).fetchall()
    for data in ok_binaries:
        final_name = Path(data[0]).parent / data[1].removesuffix(".bin")
        test_name = re.sub("-[a-f0-9]{8}$", "", data[0].removeprefix(f"{final_name}-"))
        includes.append(
            {
                "name": final_name,
                "test_name": test_name,
                "elapsed_time": data[2],
                "max_rss": data[3],
            }
        )

    with open(args.output, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["name", "test_name", "elapsed_time", "max_rss"])
        writer.writeheader()
        writer.writerows(includes)


if __name__ == "__main__":
    main()
