#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
REAL_ROOT=$(dirname "$(realpath "$ORCHESTRA_ROOT")")

for executable in $(type -a npm | grep -Po '(?<=is ).*$'); do
    EXECUTABLE_DIR=$( dirname "$(realpath "$executable")")
    if [[ "$EXECUTABLE_DIR" != "$SCRIPT_DIR" && "$EXECUTABLE_DIR" != "$REAL_ROOT"* ]]; then
        SYSTEM_NPM="$executable"
        break
    fi
done

if [ -z "${SYSTEM_NPM:-}" ]; then
    echo "System's npm not found in PATH!" > /dev/stderr
    exit 1
fi

exec "$SYSTEM_NPM" "$@"
