#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ load("/lib/make.lib.yml", "make")

#@ source_url = "https://codeload.github.com/tpoechtrager/cctools-port/tar.gz/1e3f614aff4eaae01b6cc4d29c3237c93f3322f8"
#@ source_url = "https://github.com/tpoechtrager/cctools-port/archive/cctools-877.8-ld64-253.9-1.tar.gz"

---
#@ def architectures():
x86-64: x86_64-apple-darwin11
i686: i686-apple-darwin11
arm: arm-apple-darwin11
aarch64: aarch64-apple-darwin11
#@ end


#@yaml/text-templated-strings
---
#@ def ld64_components():
#@ for name, triple in dict(architectures()).items():
toolchain/macos/(@= name @)/ld64:
  license: cctools/APPLE_LICENSE
  builds:
    default:
      configure: |
        set -x
        rm -rf "$BUILD_DIR"
        git clone --depth 1 https://github.com/tpoechtrager/cctools-port.git "$BUILD_DIR"

        cd "$BUILD_DIR/cctools"
        ./autogen.sh
        autoconf --force
        libtoolize --force
        ./configure \
          --prefix="$ORCHESTRA_ROOT" \
          --target=(@= triple @) \
          --enable-tapi-support \
          CC="clang" \
          CXX="clang++" \
          OBJC="clang" \
          CXXFLAGS="-I${BUILD_DIR}/include" \
          LDFLAGS="-L${BUILD_DIR}/lib"
      install: |
        cd "$BUILD_DIR/cctools"
        (@= make @)
        (@= make @) install
      build_dependencies:
        - host-cxx-toolchain
      dependencies:
        - host-libcxx
        - toolchain/macos/libtapi
#@ end
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  _: #@ template.replace(ld64_components())
