#@ load("@ytt:overlay", "overlay")
#@ load("/components/toolchain/lib/toolchain.lib.yml", "create_toolchain_components")

#@ def params():
toolchain_name: mipsel
triple: mipsel-unknown-linux-musl
linux_version: "6.1.4"
linux_arch_name: mips
binutils_version: "2.35"
gdb_version: "8.2.1"
musl_version: "1.1.12"
gcc_version: "9.2.0"
coreutils_version: "8.29"
extra_gcc_configure_options:
  - --with-abi=
  - --without-isl
  - --disable-libsanitizer
  - --disable-libssp
  - --disable-shared
dynamic: "0"
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components: #@ create_toolchain_components(**params())
