#@ load("@ytt:overlay", "overlay")
#@ load("/components/toolchain/lib/toolchain.lib.yml", "create_toolchain_components")
#@ load("/lib/util.lib.yml", "datavalue")

#@ def params():
toolchain_name: win64
triple: x86_64-w64-mingw32
binutils_version: "2.35"
gdb_version: "8.2.1"
mingw64_version: "6.0.0"
gcc_version: #@ str(datavalue("gcc_host_version"))
extra_gcc_configure_options:
  - --without-cloog
  - --without-isl
  - --disable-libsanitizer
  - --disable-libssp
  - --enable-shared
extra_gcc_stage2_configure_options: " --enable-threads=posix --enable-libstdcxx-threads=yes"
dynamic: "0"
custom_pkgconfig: true
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components: #@ create_toolchain_components(**params())
