#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/environment"

EXECUTABLE_NAME=$(basename "$0")
exec "$SCRIPT_DIR/root/bin/$EXECUTABLE_NAME" "$@"
