#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck disable=SC1091
source "$DIR/environment"
export REAL_ARGV0="$0"

exec "$DIR/root/bin/revng" "$@"
