#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ load("/lib/cmake.lib.yml", "typical_cmake_builds", "cmake_boost_configuration")

---
#@ def build_args():
test: true
pre_configure_script: |
  if ! test -e "$SOURCE_DIR/../qt-creator"; then
    orc clone ui/qt-creator
  fi
extra_cmake_args:
  - #@ template.replace(cmake_boost_configuration)
  #! TODO: this is really ugly hack to get the same value of QTC_SOURCE as legacy orchestra
  - -DQTC_SOURCE="$SOURCE_DIR/../qt-creator"
  - -DQTC_BUILD="$ORCHESTRA_ROOT"
build_dependencies:
  - cmake
  - glibc
  - toolchain/host/cxx-toolchain
dependencies:
  - toolchain/host/cxx-runtime
  - caliban
  - ui/graphviz
  - ui/adaptagrams
  - ui/quickqanava
  - ui/qt-creator
post_install_script: |
  ln -s qtcreator "${TMP_ROOT}${ORCHESTRA_ROOT}/bin/revng-ui"
use_asan: false
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  ui/cold-revng:
    repository: ui-cold-revng
    license: LICENSE.md
    binary_archives: private
    default_build: optimized
    builds: #@ typical_cmake_builds(**build_args())
