#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/make.lib.yml", "make")
#@ load("/lib/shell.lib.yml", "expand_args")
#@ load("/lib/optimization_flavors.lib.yml", "qmake_optimization_flavors")

---
#@ def qt_creator_plugins():
- coreplugin
- texteditor
- projectexplorer
- resourceeditor
- cpptools
- qmakeprojectmanager
- qtsupport
- cppeditor
- bineditor
#@ end

#@yaml/text-templated-strings
---
#@ def _configure_base(extra_qmake_args=[]):
#! TODO: In legacy orchestra QMAKE_RPATHDIR has +="" in debug and release but ="" in optimized. Is it intentional?
- |
  mkdir -p "$BUILD_DIR"
  cd "$BUILD_DIR";
  qmake -r "$SOURCE_DIR" \
    -spec linux-clang \
    DEFINES+="COLD_REVNG" \
    (@= expand_args(extra_qmake_args) @) \
    QMAKE_LFLAGS_RPATH= \
    QMAKE_RPATHDIR+="" \
    ONLY_PLUGINS="(@= " ".join(qt_creator_plugins()) @)"
#@ end

#@ def configure_base(**kwargs):
#@    return _configure_base(**kwargs)[0].strip()
#@ end

#@yaml/text-templated-strings
---
#@ def qt_creator_component():
repository: ui-qt-creator
license: LICENSE.GPL3-EXCEPT
default_build: #@ data.values.revng_components_default_build
builds:
  #@ for flavor, opts in qmake_optimization_flavors.items():
  #@ extra_qmake_args = opts["extra_qmake_args"]
  (@= flavor @):
    configure: #@ configure_base(extra_qmake_args=extra_qmake_args)
    install: |
      cd "$BUILD_DIR"
      (@= make @)
      (@= make @) install INSTALL_ROOT="$DESTDIR$ORCHESTRA_ROOT"
    dependencies:
      - host-libcxx
      - llvm
      - ui/qt
    build_dependencies:
      - host-c-toolchain
      - glibc
    #@ if/end opts["ndebug"] == False:
    ndebug: false
  #@ end
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  ui/qt-creator: #@ qt_creator_component()
