#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://xkbcommon.org/download/libxkbcommon-0.10.0.tar.xz"

#@yaml/text-templated-strings
---
#@ def xkbcommon_args():
license: source/LICENSE
configure: |
  mkdir -p "$BUILD_DIR/source"
  extract.sh --into "$BUILD_DIR/source" "(@= source_url @)"

  cd "$BUILD_DIR"

  find "$BUILD_DIR/source/" -name meson.build -exec sed -i "s|install\s*:\s*|install_rpath : '$RPATH_PLACEHOLDER/lib', \0|" {} \;

  CC=clang \
  meson setup \
    --buildtype plain \
    --libdir=lib \
    --prefix "$ORCHESTRA_ROOT" \
    --wrap-mode nodownload \
    -Db_ndebug=true \
    -Ddefault_library=shared \
    -Denable-wayland=false \
    -Denable-x11=true \
    -Denable-docs=false \
    "$BUILD_DIR" \
    "$BUILD_DIR/source"

build_system: ninja
build_dependencies:
  - toolchain/host/cxx-toolchain
  - glibc
dependencies:
  - ui/libbsd
  - ui/libxcb
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  ui/xkbcommon: #@ single_build_component(**xkbcommon_args())
