#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ load("/lib/cmake.lib.yml", "cmake_boost_configuration", "typical_cmake_builds")

---
#@ def build_args():
test: true
extra_cmake_args: #@ cmake_boost_configuration
build_dependencies:
  - cmake
  - glibc
  - host-cxx-toolchain
dependencies:
  - host-libcxx
  - llvm
  - revng
  - revng-c
  - boost
  - libedit
  - libfort
use_asan: false
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  caliban:
    repository: caliban
    license: LICENSE.md
    binary_archives: private
    default_build: #@ data.values.revng_components_default_build
    builds: #@ typical_cmake_builds(**build_args())
