#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ source_url = "https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz"

#@yaml/text-templated-strings
---
#@ def gmp_args():
license: COPYING
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" "(@= source_url @)"
  cd "$BUILD_DIR" && ./configure \
    --prefix="$ORCHESTRA_ROOT" \
    --enable-shared=no \
    --enable-fat \
    CFLAGS="-fPIC" \
    CXXFLAGS="-fPIC" \
    LDFLAGS="-static-libgcc"
build_system: make
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  gmp: #@ single_build_component(**gmp_args())
