#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create-component.lib.yml", "single_build_component")

#@yaml/text-templated-strings
---
#@ def args():
#@ version = "8.2.0"
#@ source_url = "https://github.com/jemalloc/jemalloc/archive/refs/tags/5.3.0.tar.gz"
license: COPYING
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" (@= source_url @)

  cd "$BUILD_DIR"

  # We need --disable-initial-exec-tls or Python tests fail:
  # https://github.com/jemalloc/jemalloc/issues/1237
  ./autogen.sh \
    --prefix="$ORCHESTRA_ROOT" \
    --disable-stats \
    --enable-shared \
    --disable-cxx \
    --disable-static
build_system: make
build_dependencies:
  - glibc
  - gcc-host-toolchain
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  jemalloc: #@ single_build_component(**args())
