#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("/lib/pip.lib.yml", "pip_package")

#@ def params():
name: lit
dependencies:
- python-base-packages
requirements: |-
  # lit version should always match clang-release and llvm version
  lit==12.0.0
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  _: #@ template.replace(pip_package(**params()))
