#@ load("@ytt:overlay", "overlay")

#@ def llvmcpy_component():
repository: llvmcpy
license: LICENSE.txt
builds:
  default:
    dependencies:
      - llvm
    configure: |
      mkdir -p "$BUILD_DIR"
    install: |
      export PYTHONPATH="$DESTDIR/lib/python"
      mkdir -p "$PYTHONPATH"
      cd "$SOURCE_DIR"
      python3 setup.py build --build-base "$SOURCE_DIR"
      python3 setup.py build --build-base "$SOURCE_DIR" install --home "$DESTDIR"
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  llvmcpy: #@ llvmcpy_component()
