#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")

#@ mpfr_version = "4.1.0"
#@ source_url = "https://www.mpfr.org/mpfr-" + mpfr_version + "/mpfr-" + mpfr_version + ".tar.xz"

#@yaml/text-templated-strings
---
#@ def mpfr_args():
license: COPYING
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" (@= source_url @)
  cd "$BUILD_DIR" && ./configure \
    --prefix="$ORCHESTRA_ROOT" \
    --with-gmp="$ORCHESTRA_ROOT" \
    --enable-shared=no \
    CFLAGS="-fPIC" \
    CXXFLAGS="-fPIC" \
    LDFLAGS="-static-libgcc"
build_system: make
dependencies:
  - gmp
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  mpfr: #@ single_build_component(**mpfr_args())
