#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create_component.lib.yml", "single_build_component")
#@ load("/lib/make.lib.yml", "make")

#@ ncurses_ver = "6.3"
#@ source_url = "https://ftp.gnu.org/pub/gnu/ncurses/ncurses-" + ncurses_ver + ".tar.gz"
#@ ncurses_major = ncurses_ver.split(".")[0]

#@yaml/text-templated-strings
---
#@ def ncurses_args():
license: COPYING
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" (@= source_url @)
  cd "$BUILD_DIR"
  ./configure \
    --enable-pc-files \
    --enable-widec \
    --with-cxx \
    --with-cxx-binding \
    --with-cxx-shared \
    --with-shared \
    --with-versioned-syms \
    --with-xterm-kbs=del \
    --with-manpage-format=normal \
    --without-ada \
    --without-assertions \
    --without-debug \
    --without-dlsym \
    --without-expanded \
    --without-gpm \
    --without-hashed-db \
    --without-profile \
    --without-tack \
    --without-tests \
    --without-trace \
    --prefix="$ORCHESTRA_ROOT" \
    --with-pkg-config-libdir="$ORCHESTRA_ROOT/lib/pkgconfig"
install: |
  cd "$BUILD_DIR"
  (@= make @)
  (@= make @) install DESTDIR="$DESTDIR"

  INSTALLDIR="${DESTDIR}${ORCHESTRA_ROOT}"

  # Adapted from ArchLinux PKGBUILD
  # fool packages looking to link to non-wide-character ncurses libraries
  for lib in ncurses ncurses++ form panel menu; do
    printf "INPUT(-l%sw)\n" "${lib}" > "$INSTALLDIR/lib/lib${lib}.so"
    ln -sv lib${lib}w.so.(@= ncurses_ver @) "$INSTALLDIR/lib/lib${lib}.so.(@= ncurses_ver @)"
    ln -sv lib${lib}w.so.(@= ncurses_ver @) "$INSTALLDIR/lib/lib${lib}.so.(@= ncurses_major @)"
    ln -sv ${lib}w.pc "$INSTALLDIR/lib/pkgconfig/${lib}.pc"
  done

  # some packages look for -lcurses during build
  printf 'INPUT(-lncursesw)\n' > "$INSTALLDIR/lib/libcursesw.so"
  ln -sv libncurses.so "$INSTALLDIR/lib/libcurses.so"

  # tic and ticinfo functionality is built in by default
  # make sure that anything linking against it links against libncursesw.so instead
  for lib in tic tinfo; do
    printf "INPUT(libncursesw.so.(@= ncurses_major @))\n" > "$INSTALLDIR/lib/lib${lib}.so"
    ln -sv libncursesw.so.(@= ncurses_ver @) "$INSTALLDIR/lib/lib${lib}.so.(@= ncurses_ver @)"
    ln -sv libncursesw.so.(@= ncurses_ver @) "$INSTALLDIR/lib/lib${lib}.so.(@= ncurses_major @)"
    ln -sv ncursesw.pc "$INSTALLDIR/lib/pkgconfig/${lib}.pc"
  done

build_dependencies:
  - gcc-host-toolchain
  - glibc
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  ncurses: #@ single_build_component(**ncurses_args())

