#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create-component.lib.yml", "single_build_component")

#@yaml/text-templated-strings
---
#@ def nghttp2_args():
#@ nghttp2_version = "1.54.0"
#@ source_url = "https://github.com/nghttp2/nghttp2/releases/download/v" + nghttp2_version + "/nghttp2-" + nghttp2_version + ".tar.xz"
license: COPYING
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" (@= source_url @)

  cd "$BUILD_DIR"

  ./configure \
    --prefix="$ORCHESTRA_ROOT" \
    --enable-lib-only \
    --disable-static
build_system: make
build_dependencies:
  - host-c-toolchain
dependencies:
  - host-libc
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  nghttp2: #@ single_build_component(**nghttp2_args())
