#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/make.lib.yml", "make")

#@yaml/text-templated-strings
---
#@ def openssl_component():
#@ source_url = "https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1q.tar.gz"
license: LICENSE
builds:
  default:
    configure: |
      mkdir -p "$BUILD_DIR"
      extract.sh --into "$BUILD_DIR" (@= source_url @)

      #@ # Note: openssldir is set to /etc/ssl; we assume that distros provide this.
      #@ # On distros that don't, the following check will fail at build-time,
      #@ # but unfortunately not at install-time when binary archives are used.
      if ! [[ -d /etc/ssl ]]; then
        echo "Error: openssldir /etc/ssl is missing in host root!" >&2
        exit 1
      fi

      cd "$BUILD_DIR"
      ./Configure \
        --prefix="$ORCHESTRA_ROOT" \
        --openssldir="/etc/ssl" \
        --libdir=lib64 \
        linux-x86_64 \
        enable-camellia \
        enable-ec \
        enable-ec2m \
        enable-sm2 \
        enable-srp \
        enable-idea \
        enable-mdc2 \
        enable-rc5 \
        no-ssl3 \
        no-ssl3-method \
        enable-asm \
        no-rfc3779 \
        no-sctp \
        no-tests \
        no-zlib \
        no-heartbeats \
        no-weak-ssl-ciphers \
        shared \
        threads
    install: |
      cd "$BUILD_DIR"
      (@= make @)
      (@= make @) install_sw DESTDIR="$DESTDIR"
      find "$DESTDIR" -name "*.a" -delete
    build_dependencies:
      - host-c-toolchain
    dependencies:
      - host-libc
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  openssl: #@ openssl_component()
