#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/make.lib.yml", "make")
#@ load("/lib/util.lib.yml", "datavalue")

#@yaml/text-templated-strings
---
#@ def python_component():
#@ python_version = "3.14.6"
#@ source_url = "https://www.python.org/ftp/python/" + python_version + "/Python-" + python_version + ".tar.xz"
license: LICENSE
builds:
  default:
    configure: |
      mkdir -p "$BUILD_DIR"
      extract.sh --into "$BUILD_DIR" (@= source_url @)

      # Implicitly force PYTHONNOUSERSITE
      sed -i \
        's/if (no_user_site_directory)/if (1)/' \
        "$BUILD_DIR/Python/initconfig.c"

      cd "$BUILD_DIR"
      patch -p1 < "${ORCHESTRA_DOTDIR}/patches/python-fixes.patch"

      # orchestra's libc has a buggy getaddrinfo; we expect users to have a newer libc
      ac_cv_buggy_getaddrinfo=no ./configure \
        --prefix="$ORCHESTRA_ROOT" \
        --libdir="${ORCHESTRA_ROOT}/lib64" \
        --enable-optimizations \
        --enable-shared \
        --enable-ipv6 \
        --with-ensurepip=install \
        --with-lto \
        --with-readline \
        --with-system-expat \
        --without-static-libpython \
        CC=gcc LDFLAGS="-fuse-ld=lld -ljemalloc"

      grep -v HAVE_SYS_AUXV_H pyconfig.h > pyconfig.h.tmp
      mv pyconfig.h.tmp pyconfig.h
    install: |
      cd "$BUILD_DIR"
      (@= make @)
      (@= make @) install DESTDIR="$DESTDIR"

      INSTALLDIR="${DESTDIR}${ORCHESTRA_ROOT}"
      ln -s python3 "${INSTALLDIR}"/bin/python
      ln -s python3-config "${INSTALLDIR}"/bin/python-config
      ln -s idle3 "${INSTALLDIR}"/bin/idle
      ln -s pydoc3 "${INSTALLDIR}"/bin/pydoc

      PY_VER=$(echo "(@= python_version @)" | grep -Po '^\d\.\d+')
      PYTHON_DIR="${INSTALLDIR}/lib/python${PY_VER}"

      # Python installs pip alongside itself, this means that there will be
      # some modules in `lib/python3.XX/site-packages` present due to this
      # component. Account for them in the orchestra infrastructure.
      mkdir -p "${INSTALLDIR}/share/orchestra/python-packages"
      find "${PYTHON_DIR}/site-packages" -maxdepth 1 -type d -printf '%f\n' | \
        grep -P '^[A-Za-z][\w_]*$' > \
          "${INSTALLDIR}/share/orchestra/python-packages/python.txt"

      # Remove the test directories, this contributes ~150MB to the install
      # size without any practical benefit for us
      rm -r "${PYTHON_DIR}/test" "${PYTHON_DIR}/idlelib/idle_test"

      if [ "$RUN_TESTS" -eq 1 ]; then
        LD_LIBRARY_PATH=$(realpath .) \
          ./python -m test -j0 \
            `# A whole bunch of these fail because we disabled USERSITE` \
            -x test_embed \
            -i test.test_cmd_line.CmdLineTest.test_empty_PYTHONPATH_issue16309 \
            `# This fails due to libc being in 'link-only'` \
            -i test.test_ctypes.test_find.FindLibraryLinux.test_find_library_with_ld \
            `# This fails due to outdated glibc` \
            -i test.test_posix.PosixTester.test_makedev \
            -i test.test_subprocess.ProcessTestCase.test_pipesize_default \
            `# This hangs indefinitely when running in a container, cause unknown` \
            -i 'test.test_socket.RDSTest.*' \
            `# This sometimes fails when run in a container` \
            -x test_perf_profiler \
            -i test.test_struct.StructTest.test_endian_table_init_subinterpreters
      fi
    build_dependencies:
      - host-c-toolchain
    dependencies:
      - bzip2
      - expat
      - libffi
      - libxcrypt
      - openssl
      - readline
      - sqlite
      - libb2
      - xz
      - zstd
      - host-libc
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  python: #@ python_component()
