#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("/lib/pip.lib.yml", "pip_package")

#@ def params():
name: python-base-packages
dependencies:
- python
requirements: |-
  wheel
  no-manylinux
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  _: #@ template.replace(pip_package(**params()))
