#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/make.lib.yml", "make")
#@ load("/lib/optimization-flavors.lib.yml", "typical_project_flavors")

#@yaml/text-templated-strings
---
#@ def qemu_component(target_suffixes, extra_cflags="", use_asan=False):
repository: qemu
license: LICENSE
default_build: optimized
builds:
  #@ for flavor, f_options in typical_project_flavors(use_asan=use_asan).items():
    #@ build_type = f_options["cmake_build_type"]
    #@ cflags = f_options["extra_compiler_flags"]
    #@ ndebug = f_options["ndebug"]
    (@= flavor @):
      configure: |
        mkdir -p "$BUILD_DIR"
        cd "$BUILD_DIR";
        # export PATH="$ORCHESTRA_ROOT/link-only/bin:$ORCHESTRA_ROOT/lib64/llvm/llvm/bin:$PATH";
        which -a clang;
        "$SOURCE_DIR/configure" \
          --cc="(@= data.values.regular_c_compiler @)" \
          --cxx="(@= data.values.regular_cxx_compiler @)" \
          --prefix="$ORCHESTRA_ROOT" \
          --disable-plugins \
          --target-list=" \
            (@ for target_suffix in target_suffixes: -@)
            arm-(@= target_suffix @) \
            aarch64-(@= target_suffix @) \
            i386-(@= target_suffix @) \
            mips-(@= target_suffix @) \
            mipsel-(@= target_suffix @) \
            s390x-(@= target_suffix @) \
            x86_64-(@= target_suffix @) \
            (@ end -@)
          " \
          --disable-werror \
          --disable-docs \
          --disable-kvm \
          --disable-tools \
          --disable-system \
          --disable-libnfs \
          --disable-vde \
          --disable-gnutls \
          --disable-cap-ng \
          -Dvhost_user=disabled \
          -Dxkbcommon=disabled \
          --libdir="$ORCHESTRA_ROOT/lib"  \
          (@ if build_type == "Debug": @)--enable-debug (@ end @)\
          --extra-cflags="(@= cflags @) (@= extra_cflags @) -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-but-set-variable"
      install: |
        cd "$BUILD_DIR"
        (@= make @) install
      build_dependencies:
        - host-c-toolchain
        - llvm
      dependencies:
        - zlib
        - glib
      #@ if/end ndebug == False:
      ndebug: false
  #@ end
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  qemu: #@ qemu_component(["linux-user", "libtcg"], "-fPIC")
  #! TODO: we need to make CSAA compatible with optimized code so that we can
  #!       then just add -fembed-bitcode to a regular build.
  #!       Note that it might not be hard, we haven't tried.
  #!       In order to achieve this, we should also switch from using
  #!       GEN_LLVM_HELPERS to CONFIG_LLVM_HELPERS. However, we can't use that
  #!       in common code, so some extra work needs to be done there as well. If
  #!       we try to use CONFIG_LLVM_HELPERS where not allowed, we'll get a nice
  #!       "attempt to use a poisoned identifier" error.
  qemu-helpers: #@ qemu_component(["llvm-helpers"], "-fPIC -Wno-gcc-compat -DGEN_LLVM_HELPERS -O0 -Xclang -disable-O0-optnone -fembed-bitcode")
