#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  revng-development:
    builds:
      default:
        dependencies:
          - test/revng-prss
          - test/revng-db
          - test/revng
          - revng-ui-web
          - revng-ui-native
          - llvm-documentation
          - revng-distributable
          - revng-distributable-public-demo
        configure: mkdir -p "$BUILD_DIR"
        install: echo "Nothing to do"
