#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("/lib/pip.lib.yml", "pip_package")

#@ def params():
name: revng-python-dependencies
dependencies:
#! TODO: Fix problem with python package using common dependecies and causing
#! conflicts
- revng-qa-python-dependencies
- pyyaml
- cython
- uvloop
- llvm
- libpq
requirements: |-
  # Python language checkers/formatters
  black>=25.1.0,<26.0
  flake8>=7.0.0,<8.0
  flake8-breakpoint>=1.1.0,<2.0
  flake8-builtins>=3.1.0,<4.0
  flake8-comprehensions>=3.10.1,<4.0
  flake8-eradicate>=1.4.0,<2.0
  flake8-simplify>=0.19.3,<1.0
  pep8-naming>=0.13.3,<1.0
  isort>=8.0.0,<9.0
  codespell>=2.2.2,<3.0
  mypy==1.20.2

  # Python types, needed for mypy to work correctly
  types-backports
  types-PyYAML
  types-requests
  types-urllib3
  # This specific versions because newer ones requires maturin, the rust setup tool, 
  # and inside orchestra it fails to compile because it doesn't link against libc.
  types-jsonschema>=4.17.0.10,<4.18.0

  # cmake-format executable
  cmakelang

  # Applications/Script dependencies
  Jinja2
  aiohttp>=3.14.3,<4.0
  websockets>=10.4
  https://github.com/revng/grandiso-networkx/archive/043ce4b.tar.gz
  https://github.com/revng/jsonschema/archive/c17ffb2.tar.gz
  jsonschema-to-typeddict>=1.4.2,<2.0
  networkx>=3.3
  pefile
  pycparser
  pydot>=3.0.2
  pyelftools==0.32
  zstandard
  click>=8.3.0,<9.0
  click-option-group>=0.5.9,<1.0
  starlette[full]>=0.52.1
  psycopg[c,pool]>=3.3.3,<4.0
  hypercorn>=0.18.0,<1.0

  # This is our fork of the python-idb package that includes some fixes.
  https://github.com/revng/python-idb/archive/08ba07a.tar.gz

  pytest
  pytest-asyncio
  requests
  requests-toolbelt
  psutil
  build
  https://github.com/revng/llvmcpy/archive/9eca23b.tar.gz

  xdg

  marko
  mkdocs<2.0
  mkdocs-graphviz==2.0.2
  mkdocs-toggle-sidebar-plugin
  mkdocs-material

  yachalk
  yq

  # Not needed directly by revng, used by mass-testing
  boto3-stubs[s3]
  boto3<=1.35.99
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  _: #@ template.replace(pip_package(**params()))
