#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create-component.lib.yml", "single_build_component")

#@ commit = "223f4b9723d8fb7c83c286b6b4ad75dff18985c4"

#@yaml/text-templated-strings
---
#@ def win32metadata_args():
configure: |
  mkdir -p "$BUILD_DIR"
  git init "$BUILD_DIR/win32metadata"
  cd "$BUILD_DIR/win32metadata"
  git fetch --depth 1 \
    "https://github.com/microsoft/win32metadata.git" \
    "(@= commit @)"
  git checkout FETCH_HEAD

install: |
  cd "$BUILD_DIR"
  mkdir -p "${DESTDIR}${ORCHESTRA_ROOT}/share/win32metadata"
  cp -a win32metadata/generation "${DESTDIR}${ORCHESTRA_ROOT}/share/win32metadata/"
  cp -a win32metadata/sources "${DESTDIR}${ORCHESTRA_ROOT}/share/win32metadata/"
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  win32metadata: #@ single_build_component(**win32metadata_args())
