#!/usr/bin/env bash
#
# This file is distributed under the MIT License. See LICENSE.md for details.
#

set -euo pipefail

PORT_FILE=$(mktemp --tmpdir tmp.revng.port-file.XXXXXXXXXX)
CACHE_FOLDER=$(mktemp -d --tmpdir tmp.revng.npm.XXXXXXXXXX)
REPO_PID=0
SCRIPT_FOLDER="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

cleanup() {
    trap - SIGINT SIGTERM ERR EXIT
    if [ $REPO_PID -gt 0 ]; then kill $REPO_PID; fi
    rm -rf -- "$PORT_FILE" "$CACHE_FOLDER"
}
trap cleanup SIGINT SIGTERM ERR EXIT

readarray -t CACHES < <(echo "$ORCHESTRA_NODE_CACHE" | tr ':' '\n')
"$SCRIPT_FOLDER/../libexec/static-npm-registry" "$PORT_FILE" "${CACHES[@]}" &
REPO_PID=$!

while [ -z "$(cat "$PORT_FILE")" ]; do sleep 0.1s; done
PORT=$(cat "$PORT_FILE")
npm.original --registry="http://127.0.0.1:$PORT" --cache="$CACHE_FOLDER" "$@"
