#!/bin/bash

set -x
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
FILES=$(find "$DIR" -name "*.docker")

for FILE in $FILES; do
    FILE_PATH=$(realpath "$FILE")
    "$DIR/build" "$(basename "${FILE%.*}")"
done
