#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  host-c-toolchain:
    builds:
      default:
        dependencies:
          - glibc
          - toolchain/host/binutils
          - clang-release
          - jemalloc
        install: exit 0
        configure: mkdir -p "$BUILD_DIR"

  host-cxx-toolchain:
    builds:
      default:
        dependencies:
          - host-c-toolchain
          - clang-runtime
        install: exit 0
        configure: mkdir -p "$BUILD_DIR"

  #! This is not actually the C standard library, since the host OS should
  #! provide it. This is just the C runtime in a larger sense.
  host-libc:
    builds:
      default:
        dependencies:
          - jemalloc
        install: exit 0
        configure: mkdir -p "$BUILD_DIR"

  host-libcxx:
    builds:
      default:
        dependencies:
          - host-libc
          - clang-runtime
          - gcc-runtime
        install: exit 0
        configure: mkdir -p "$BUILD_DIR"
